version: "3.9"

services:
  nginx:
    build:
      context: .
      dockerfile: infra/nginx/Dockerfile
    container_name: portivox-nginx
    ports:
      - "80:80"
    depends_on:
      gateway:
        condition: service_healthy

  gateway:
    build:
      context: .
      dockerfile: apps/gateway-server/Dockerfile
    container_name: portivox-gateway
    environment:
      GATEWAY_PORT: "8080"
      GATEWAY_WS_PORT: "7000"
      ROOT_DOMAIN: "app.localtest.me"
      MAX_REQUEST_BODY_BYTES: "1048576"
      TUNNEL_RESPONSE_TIMEOUT_MS: "20000"
      WS_IDLE_TIMEOUT_MS: "30000"
      REGISTRY_BACKEND: "redis"
      REDIS_URL: "redis://redis:6379"
      REDIS_KEY_PREFIX: "portivox:registry"
      REGISTRY_LEASE_TTL_MS: "30000"
    ports:
      - "7000:7000"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8080/healthz"]
      interval: 10s
      timeout: 3s
      retries: 5
    depends_on:
      redis:
        condition: service_started

  gateway-2:
    build:
      context: .
      dockerfile: apps/gateway-server/Dockerfile
    container_name: portivox-gateway-2
    profiles: ["scale"]
    environment:
      GATEWAY_PORT: "8081"
      GATEWAY_WS_PORT: "7001"
      ROOT_DOMAIN: "app.localtest.me"
      MAX_REQUEST_BODY_BYTES: "1048576"
      TUNNEL_RESPONSE_TIMEOUT_MS: "20000"
      WS_IDLE_TIMEOUT_MS: "30000"
      REGISTRY_BACKEND: "redis"
      REDIS_URL: "redis://redis:6379"
      REDIS_KEY_PREFIX: "portivox:registry"
      REGISTRY_LEASE_TTL_MS: "30000"
      GATEWAY_NODE_ID: "gateway-2"
    ports:
      - "7001:7001"
    depends_on:
      redis:
        condition: service_started

  redis:
    image: redis:7-alpine
    container_name: portivox-redis
    command: ["redis-server", "--appendonly", "no"]
    ports:
      - "6379:6379"

  sample-local-app:
    image: hashicorp/http-echo:1.0.0
    container_name: portivox-sample-local-app
    command: ["-text=hello-from-docker-local-app", "-listen=:3000"]
    expose:
      - "3000"

  client:
    build:
      context: .
      dockerfile: apps/tunnel-client/Dockerfile
    container_name: portivox-client
    environment:
      TUNNEL_GATEWAY_URL: "ws://gateway:7000/connect"
      TUNNEL_LOCAL_URL: "http://sample-local-app:3000"
      TUNNEL_SUBDOMAIN: "demo"
      LOCAL_REQUEST_TIMEOUT_MS: "15000"
      MAX_LOCAL_RESPONSE_BODY_BYTES: "2097152"
    depends_on:
      gateway:
        condition: service_healthy
      sample-local-app:
        condition: service_started

networks:
  default:
    name: portivox-network

