export type GatewayConfig = {
  gatewayPort: number;
  wsPort: number;
  rootDomain: string;
  tunnelResponseTimeoutMs: number;
  wsIdleTimeoutMs: number;
  maxRequestBodyBytes: number;
  authRequired: boolean;
  authApiKeys: string;
  authApiKeyScopes: string;
  authJwtSecret: string;
  registryBackend: "memory" | "redis";
  redisUrl: string;
  redisKeyPrefix: string;
  registryLeaseTtlMs: number;
  nodeId: string;
  maxConcurrentStreamsPerTunnel: number;
  streamIdleTimeoutMs: number;
  maintenanceMode: boolean;
  startupGraceMs: number;
  auditExportJsonlPath: string;
  auditExportWebhookUrl: string;
  auditExportWebhookTimeoutMs: number;
  auditExportWebhookSecret: string;
  auditExportWebhookMaxRetries: number;
  auditExportWebhookRetryBaseMs: number;
  auditExportDeadLetterJsonlPath: string;
  apiVersion: string;
  apiDeprecationEnabled: boolean;
  apiSunsetDate: string;
  apiRateLimitReadPerMin: number;
  apiRateLimitWritePerMin: number;
  apiRateLimitAdminPerMin: number;
  ingressRateLimitPerMin: number;
  corsAllowedOrigins: string;
  corsAllowCredentials: boolean;
  securityHeadersEnabled: boolean;
  idempotencyEnabled: boolean;
  idempotencyTtlMs: number;
  tcpTunnelEnabled: boolean;
  tcpTunnelBindHost: string;
  tcpPublicHost: string;
  tcpPublicPortStart: number;
  tcpPublicPortEnd: number;
  httpPublicPortMode: boolean;
  ipProtectionDefault: boolean;
  tcpConnectionRateLimit: number;
  gatewayPublicBaseUrl: string;
};

export type ClientConfig = {
  gatewayUrl: string;
  localUrl: string;
  localTimeoutMs: number;
  maxLocalResponseBodyBytes: number;
  responseChunkBytes: number;
  heartbeatIntervalMs: number;
};

export function loadGatewayConfig(): GatewayConfig;
export function loadClientConfig(): ClientConfig;
